FROM keichi/sind-base

RUN apt-get update && \
    apt-get install -y --no-install-recommends slurmdbd && \
    rm -rf /var/lib/apt/lists/*

COPY entrypoint-database.sh /docker-entrypoint.sh
COPY slurmdbd.conf /etc/slurm/slurmdbd.conf

RUN chmod 600 /etc/slurm/slurmdbd.conf && chown slurm:slurm /etc/slurm/slurmdbd.conf

ENTRYPOINT ["/docker-entrypoint.sh"]
