FROM keichi/sind-base

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends slurmd

RUN install -m 755 -o slurm -g slurm -d /var/spool/slurmd

COPY entrypoint-worker.sh /docker-entrypoint.sh
COPY slurm.conf /etc/slurm/slurm.conf

ENTRYPOINT ["/docker-entrypoint.sh"]
