FROM keichi/sind-base

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt \
    apt-get update && \
    apt-get install -y --no-install-recommends slurmdbd

COPY entrypoint-database.sh /docker-entrypoint.sh
COPY slurmdbd.conf /etc/slurm/slurmdbd.conf

RUN chmod 600 /etc/slurm/slurmdbd.conf && chown slurm:slurm /etc/slurm/slurmdbd.conf

ENTRYPOINT ["/docker-entrypoint.sh"]
